import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

// 1. Initialize the Gemini client with your environment variable
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const { message } = await req.json();

    if (!message) {
      return NextResponse.json(
        { error: "Message is required" },
        { status: 400 }
      );
    }

    // 2. Call the real Gemini API with the user's message
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash", // We use the fast and highly capable Gemini 2.5 Flash model
      contents: message,
      config: {
        // 3. Set your bot's identity and system instructions here
        systemInstruction: `
          You are Ajay's AI Marketing Lab assistant. 
          Provide highly professional, structured, and actionable marketing advice on topics like SEO, PPC Ads, Social Media, and Content Strategy.
          Keep your tone encouraging, modern, and professional. 
          Use bullet points and emojis to make your reports clean and easy to read.
        `,
      },
    });

    // 4. Extract the actual text response generated by Gemini
    const reply = response.text || "I was unable to generate a marketing recommendation. Please try again.";

    // 5. Return the live AI response back to your frontend
    return NextResponse.json({
      reply
    });

  } catch (error) {
    console.error("Gemini API Error:", error);
    
    return NextResponse.json(
      {
        error: "Failed to connect to Gemini API"
      },
      {
        status: 500
      }
    );
  }
}